package pl.lodz.p.tewi;

public class MainFrame extends javax.swing.JFrame {

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem15 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kryptografia");
        setResizable(false);

        jDesktopPane1.setBackground(new java.awt.Color(51, 51, 255));

        jMenu1.setText("Algorytmy symetryczne");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("DES");
        jMenuItem1.setName("des"); // NOI18N
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem7.setText("TripleDES");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem9.setText("DESX");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("AES");
        jMenuItem2.setName("aes"); // NOI18N
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem8.setText("One Time Pad");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Algorytmy asymetryczne");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setText("RSA");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem4.setText("Plecakowy");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem5.setText("ElGamal");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem6.setText("Rabin");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Podpisy cyfrowe");

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem11.setText("Podpis cyfrowy RSA");
        jMenuItem11.setName("PodpisCyfrowyRSA"); // NOI18N
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem12.setText("Podpis cyfrowy ElGamal");
        jMenuItem12.setName("PodpisCyfrowyElGamal"); // NOI18N
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem12);

        jMenuItem13.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem13.setText("Podpis cyfrowy DSA");
        jMenuItem13.setName("PodpisCyfrowyDSA"); // NOI18N
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem13);

        jMenuItem14.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem14.setText("Podpis cyfrowy Schnorra");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SchnorrActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem14);
        jMenu3.add(jSeparator1);

        jMenuItem15.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem15.setText("Ślepy podpis cyfrowy RSA");
        jMenuItem15.setName("SlepyPodpisCyfrowy"); // NOI18N
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem15);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        DESFrame desframe=new DESFrame ("Algorytm DES", false, true, true, true) ;
        desframe.setTitle("Algorytm DES");
        desframe.setName("Algorytm DES");
        desframe.setVisible(true);  
        jDesktopPane1.add(desframe);
        desframe.moveToFront();    
        
       
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
       TripleDESFrame tripledesframe=new TripleDESFrame ("Algorytm TripleDES", false, true, true, true) ;
        tripledesframe.setTitle("Algorytm TripleDES");
        tripledesframe.setName("Algorytm TripleDES");
        tripledesframe.setVisible(true);  
        jDesktopPane1.add(tripledesframe);
        tripledesframe.moveToFront();    
        
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        OTPFrame otpframe=new OTPFrame ("Algorytm OTP", false, true, true, true) ;
        otpframe.setTitle("Algorytm OTP");
        otpframe.setName("Algorytm OTP");
        otpframe.setVisible(true);  
        jDesktopPane1.add(otpframe);
        otpframe.moveToFront(); 
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        AESFrame aesframe=new AESFrame ("Algorytm AES", false, true, true, true) ;
        aesframe.setTitle("Algorytm AES");
        aesframe.setName("Algorytm AES");
        aesframe.setVisible(true);  
        jDesktopPane1.add(aesframe);
        aesframe.moveToFront();    
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        DESXFrame desxframe=new DESXFrame ("Algorytm DESX", false, true, true, true) ;
        desxframe.setTitle("Algorytm DESX");
        desxframe.setName("Algorytm DESX");
        desxframe.setVisible(true);  
        jDesktopPane1.add(desxframe);
        desxframe.moveToFront();    
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        RSAFrame rsaframe=new RSAFrame ("Algorytm RSA", false, true, true, true) ;
        rsaframe.setTitle("Algorytm RSA");
        rsaframe.setName("Algorytm RSA");
        rsaframe.setVisible(true);  
        jDesktopPane1.add(rsaframe);
        rsaframe.moveToFront();  
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        PlecakowyFrame Plecakowyframe=new PlecakowyFrame ("Algorytm Plecakowy", false, true, true, true) ;
        Plecakowyframe.setTitle("Algorytm Plecakowy");
        Plecakowyframe.setName("Algorytm Plecakowy");
        Plecakowyframe.setVisible(true);  
        jDesktopPane1.add(Plecakowyframe);
        Plecakowyframe.moveToFront();  
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        ElGamalFrame ElGamalframe=new ElGamalFrame ("Algorytm ElGamal", false, true, true, true) ;
        ElGamalframe.setTitle("Algorytm ElGamal");
        ElGamalframe.setName("Algorytm ElGamal");
        ElGamalframe.setVisible(true);  
        jDesktopPane1.add(ElGamalframe);
        ElGamalframe.moveToFront();  
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        RabinFrame Rabinframe=new RabinFrame ("Algorytm Rabina", false, true, true, true) ;
        Rabinframe.setTitle("Algorytm Rabina");
        Rabinframe.setName("Algorytm Rabina");
        Rabinframe.setVisible(true);  
        jDesktopPane1.add(Rabinframe);
        Rabinframe.moveToFront();  
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        PodpisRSAFrame podpisRSAframe=new PodpisRSAFrame ("Podpis cyfrowy RSA", false, true, true, true) ;
        podpisRSAframe.setTitle("Podpis cyfrowy RSA");
        podpisRSAframe.setName("Podpis cyfrowy RSA");
        podpisRSAframe.setVisible(true);  
        jDesktopPane1.add(podpisRSAframe);
        podpisRSAframe.moveToFront();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        PodpisElGamalFrame podpisElGamalframe=new PodpisElGamalFrame ("Podpis cyfrowy ElGamal", false, true, true, true) ;
        podpisElGamalframe.setTitle("Podpis cyfrowy ElGamal");
        podpisElGamalframe.setName("Podpis cyfrowy ElGamal");
        podpisElGamalframe.setVisible(true);  
        jDesktopPane1.add(podpisElGamalframe);
        podpisElGamalframe.moveToFront();
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        SlepyPodpisRSAFrame slepypodpisRSAframe=new SlepyPodpisRSAFrame ("Ślepy podpis cyfrowy RSA", false, true, true, true) ;
        slepypodpisRSAframe.setTitle("Ślepy podpis cyfrowy RSA");
        slepypodpisRSAframe.setName("Ślepy podpis cyfrowy RSA");
        slepypodpisRSAframe.setVisible(true);  
        jDesktopPane1.add(slepypodpisRSAframe);
        slepypodpisRSAframe.moveToFront();

    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        PodpisDSAFrame podpisDSAframe=new PodpisDSAFrame ("Podpis cyfrowy DSA", false, true, true, true) ;
        podpisDSAframe.setTitle("Podpis cyfrowy DSA");
        podpisDSAframe.setName("Podpis cyfrowy DSA");
        podpisDSAframe.setVisible(true);  
        jDesktopPane1.add(podpisDSAframe);
        podpisDSAframe.moveToFront();
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void SchnorrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SchnorrActionPerformed
        PodpisSchnorrFrame podpisSchnorrframe=new PodpisSchnorrFrame ("Podpis cyfrowy Schnorra", false, true, true, true) ;
        podpisSchnorrframe.setTitle("Podpis cyfrowy Schnorra");
        podpisSchnorrframe.setName("Podpis cyfrowy Schnorra");
        podpisSchnorrframe.setVisible(true);  
        jDesktopPane1.add(podpisSchnorrframe);
        podpisSchnorrframe.moveToFront();
    }//GEN-LAST:event_SchnorrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
